[
{
    imgUrl: "src/assets/emages/apple.png",
    title: "Macbook pro",
    cate: "Laptop",
    prise: "$ 150000",
    id: 1,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/apple1.png",
    title: "Macbook Pro",
    cate: "Laptop",
    prise: "$ 150000",
    id: 2,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/apple2.png",
    title: "Macbook air",
    cate: "Laptop",
    prise: "$ 150000",
    id: 3,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/apple3.png",
    title: "Macbook Pro",
    cate: "Laptop",
    prise: "$ 150000",
    id: 4,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/apple4.png",
    title: "Macbook Pro",
    cate: "Laptop",
    prise: "$ 150000",
    id: 5,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/apple5.png",
    title: "Macbook Pro",
    cate: "Laptop",
    prise: "$ 150000",
    id: 6,
    button: "Add to cart",
    button1: "View",
  },

  {
    imgUrl: "src/assets/emages/dell.png",
    title: "Dell inspiron",
    cate: "Laptop",
    prise: "$ 50000",
    id: 7,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/dell1.png",
    title: "Dell inspiron 5430",
    cate: "Laptop",
    prise: "$ 50000",
    id: 8,
    button: "Add to cart",
    button1: "View",
  },

  {
    imgUrl: "src/assets/emages/dell3.png",
    title: "Dell inspiron 15300",
    cate: "Laptop",
    prise: "$ 50000",
    id: 10,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/dell4.png",
    title: "Dell",
    cate: "Laptop",
    prise: "$ 50000",
    id: 11,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/dell5.png",
    title: "Macbook Pro",
    cate: "Laptop",
    prise: "$ 50000",
    id: 12,
    button: "Add to cart",
    button1: "View",
  },

  {
    imgUrl: "src/assets/emages/iphone.png",
    title: "Dell",
    cate: "Mobiles",
    prise: "$ 50000",
    id: 13,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/iphone1.png",
    title: "i phone13 pro",
    cate: "Mobiles",
    prise: "$ 50000",
    id: 14,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/iphone2.png",
    title: "i phone11",
    cate: "Mobiles",
    prise: "$ 50000",
    id: 15,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/iphone3.png",
    title: "i phone 5s",
    cate: "Mobiles",
    prise: "$ 50000",
    id: 16,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/iphone4.png",
    title: "i phone12",
    cate: "Mobiles",
    prise: "$ 50000",
    id: 17,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/iphone5.png",
    title: "apple6",
    cate: "Mobiles",
    prise: "$ 50000",
    id: 18,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/hp.png",
    title: "hp",
    cate: "Laptop",
    prise: "$ 50000",
    id: 19,
    button: "Add to cart",
    button1: "View",
  },

  {
    imgUrl: "src/assets/emages/hp1.png",
    title: "hp gaming",
    cate: "Laptop",
    prise: "$ 50000",
    id: 20,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/hp2.png",
    title: "hp pavelion dv-7",
    cate: "Laptop",
    prise: "$ 50000",
    id: 21,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/hp3.png",
    title: "hp",
    cate: "Laptop",
    prise: "$ 50000",
    id: 22,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/hp4.png",
    title: "hp pavelion",
    cate: "Laptop",
    prise: "$ 50000",
    id: 23,
    button: "Add to cart",
    button1: "View",
  },

  {
    imgUrl: "src/assets/emages/faishon.png",
    title: "Full Combo",
    cate: "Fashion",
    prise: "$ 50000",
    id: 24,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/faishon1.png",
    title: "Three preese",
    cate: "Fashion",
    prise: "$ 5000",
    id: 25,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/faishon2.png",
    title: "Kid's Tshirt",
    cate: "Fashion",
    prise: "$ 500",
    id: 26,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/faishon3.png",
    title: "Kid's shirt",
    cate: "Fashion",
    prise: "$ 400",
    id: 27,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/faishon4.png",
    title: "jokey paint",
    cate: "Fashion",
    prise: "$ 40000",
    id: 28,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/shoes.png",
    title: "Addidas",
    cate: "Shoes",
    prise: "$ 500",
    id: 29,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/shoes1.png",
    title: "Nike Zoom",
    cate: "Shoes",
    prise: "$ 5000",
    id: 30,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/shoes2.png",
    title: "Nike",
    cate: "Shoes",
    prise: "$ 4000",
    id: 31,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/shoes3.png",
    title: "Shoes",
    cate: "Shoes",
    prise: "$ 3000",
    id: 32,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/airdop.png",
    title: "Airpod",
    cate: "Electronics",
    prise: "$ 50000",
    id: 33,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/boat.png",
    title: "Boat rokerz",
    cate: "Electronics",
    prise: "$ 5000",
    id: 34,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/boat1.png",
    title: "Boat pro",
    cate: "Electronics",
    prise: "$ 4000",
    id: 35,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/boat4.png",
    title: "Boat",
    cate: "Electronics",
    prise: "$ 3000",
    id: 36,
    button: "Add to cart",
    button1: "View",
  },
  {
    imgUrl: "src/assets/emages/sony3.png",
    title: "Sony",
    cate: "Electronics",
    prise: "$ 2000",
    id: 37,
    button: "Add to cart",
    button1: "View",
  },
];